version: '3.9'

services:
  backend:
    build: ./backend
    container_name: FotoCropper-fastAPI
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: FotoCropper-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
