app = "document-photo"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]


[[vm]]
  memory = '5gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
