app = "document-photo"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines= true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]


[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
